version: "3"

services:
  api:
    image: node:17.4
    user: "node"                               
    working_dir: /home/node/app                
    # environment:
    #   - NODE_ENV=production                   
    #                                           
    #
    depends_on:
      - mongodb                                           
    ports:
        - "3500:3500"                           
    volumes:
      - ./api:/home/node/app                                                                                                                   
    command: bash -c "npm install && npm run dev"    
                                                               
  mongodb:
    image: mongo:4.4.4
    # environment:
    #   MONGO_INITDB_ROOT_USERNAME: root
    #   MONGO_INITDB_ROOT_PASSWORD: rootpassword
    ports:
      - 27018:27017
    volumes:
      - mongodb:/data/db

  ui:
    build: ./ui
    image: ui
    command: npm start
    ports:
      - "3000:3000"
    volumes:
      - ./ui:/usr/src/app
      - /usr/src/app/node_modules
volumes:
  mongodb: {}
